export default {
  devices: {
    setIsUpdating: 'devices.setIsUpdating',
    setIsForceUpdating: 'devices.setIsForceUpdating',
    setEditMode: 'devices.setEditMode',
    updateDevices: 'devices.updateDevices',
    setErrorMessage: 'devices.setErrorMessage',
    clearErrorMessage: 'devices.clearErrorMessage',
    setDeviceStatus: 'devices.setDeviceStatus',
    setDeviceUpdating: 'devices.setDeviceUpdating',
    addDevice: 'devices.addDevice',
    removeDevice: 'devices.removeDevice',
    setDeviceName: 'devices.setDeviceName',
  },
  forms: {
    login: {
      updateUsername: 'forms.login.updateUsername',
      updatePassword: 'forms.login.updatePassword',
      cleanUsername: 'forms.login.cleanUsername',
      displayGenericError: 'forms.login.displayGenericError',
      displayError: 'forms.login.displayError',
      clearError: 'forms.login.clearError',
      clear: 'forms.login.clear',
      clearUsername: 'forms.login.clearUsername',
      clearPassword: 'forms.login.clearPassword',
      isFormLoading: 'forms.login.isFormLoading',
      submit: 'forms.login.submit',
    },
  },
  user: {
    setUsername: 'user.setUsername',
    setPassword: 'user.setPassword',
    setFullName: 'user.setFullName',
    setLoggingOut: 'user.setLoggingOut',
    logOut: 'user.logOut',
  },
};
